name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:   
      - name: build go binary
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          workflow: go.yml
          wait-for-completion: false
          token: "${{ secrets.REPOSITORY_TOKEN }}"